apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-voting-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dockersamples/example-voting-app.git
    targetRevision: main
    path: k8s-specifications
  destination:
    server: https://kubernetes.default.svc
    namespace: eexamplevotingapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
